<?php
/* Copyright (c) 2009 by Joseph Parsons

 * This file is a part of Fliler.
 * Fliler is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

 * Fliler is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License along with Fliler.  If not, see <http://www.gnu.org/licenses/>. */

$exts = array(
'audio' => array('aac','aif','au','cda','fla','m4a','midi','mp2','mp3','mpa','ogg','ra','raw','snd','wav','wma'),
'compressed' => array('7z','cab','deb','bz','bz2','gz','gzip','jar','pkg','rar','rpm','tar','tgz','zip'),
'common' => array('avi','doc','exe','gif','htm','html','ini','mov','mp3','mp4','odt','php','png','ppt','wav','xls','zip'),
'database' => array('accdb','accdt','csv','mdb','sql','wdb',),
'dev' => array('bsh','c','cc','cpp','cs','java','jsp','lsp','mak','make','nt','pl','rb','sh','tcl','vb'),
'disk' => array('dsk','iso','vcd'),
'document' => array('abw','doc','docm','docx','dot','dotm','dotx','kwd','lwp','odm','odt','one','ott','pub','rtf','sdw','stw','sxw','text','txt','xml','wp','wp6','wp7','wpd','wps','wpt','pdf'),
'exec' => array('app','bin','com','exe','sh','vb','ws'),
'fontcur' => array('ani','cur','fnt','fon','otf','ttf'),
'game' => array('frz','gb','gba','gbc','gg','j64','jag','n64','nds','nes','npc','pj','rom','sav','smc','sms','srm','v64','xbe','xex','z64'),
'image' => array('ai','apng','art','bmf','bmp','cdr','csh','gif','ico','icon','img','jp2','jpe','jpeg','jpf','jpg','mng','msp','odg','pct','png','pps','psd','psp','raw','svg','tif','tiff','wmf','xcf'),
'presentation' => array('kpr','odp','otp','pot','potx','pps','ppsm','ppsx','ppt','pptm','pptx','sti','sxi'),
'settings' => array('cfg','ini','reg'),
'spreadsheet' => array('123','csv','ksp','ods','ots','sdc','stc','sxc','wks','xls','xlsm','xlsx','xlt','xltx'),
'sys' => array('cab','cur','dat','inf','lnk','sys'),
'video' => array('3gp','asf','asx','avi','divx','dv','flv','m4v','mov','mp4','mpeg','mpg','ogm','qt','raw','rm','swf','wmv','xvid'),
'vm' => array('dsk','sav','vdi','vfd','vhd','vmc','vmdk','vmx','vsv','vud'),
'web' => array('asp','aspx','cfm','cgi','css','htm','html','java','js','jsp','mhtml','php','php3','php4','php5','phtml','rss','shtml','wml','xhtml','xlt','xml','xsl'),
'text' => array('cfg','ini','svg','txt','text'),
);

$mimes = array(
'3gp' => 'audio/3gpp',
'3gpp' => 'audio/3gpp',
'aac' => 'audio/aac',
'aiff' => 'audio/x-aiff',
'asf' => 'video/x-ms-asf',
'bmp' => 'image/bmp',
'crw' => 'image/x-canon-crw',
'cur' => 'image/x-win-bitmap',
'divx' => 'video/divx',
'djv' => 'image/vnd.djvu',
'djvu' => 'image/vnd.djvu',
'dng' => 'image/x-adobe-dng',
'doc' => 'application/msword',
'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
'dot' => 'application/msword',
'dotx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
'eps' => 'image/x-eps',
'flac' => 'audio/flac',
'flv' => 'video/flv',
'gif' => 'image/gif',
'html' => 'text/html',
'htm' => 'text/html',
'ico' => 'image/vnd.microsoft.icon',
'icns' => 'image/x-icns',
'jpe' => 'image/jpeg',
'jpeg' => 'image/jpeg',
'jpg' => 'image/jpeg',
'm3u' => 'audio/m3u',
'm4a' => 'audio/x-m4a',
'm4v' => 'video/x-m4v',
'mid' => 'audio/midi',
'midi' => 'audio/midi',
'wmp' => 'video/x-ms-wmp',
'mng' => 'audio/x-mng',
'mov' => 'video/quicktime',
'mp2' => 'audio/mp2',
'mp3' => 'audio/mpeg',
'mp4' => 'video/mp4',
'mpe' => 'video/mpeg',
'mpeg' => 'video/mpeg',
'mpg' => 'video/mpeg',
'odf' => 'application/vnd.oasis.opendocument.formula',
'odg' => 'application/vnd.oasis.opendocument.graphics',
'odm' => 'application/vnd.oasis.opendocument.text-master',
'odp' => 'application/vnd.oasis.opendocument.presentation',
'ods' => 'application/vnd.oasis.opendocument.spreadsheet',
'odt' => 'application/vnd.oasis.opendocument.text',
'ogg' => 'audio/ogg',
'oth' => 'application/vnd.oasis.opendocument.text-web',
'otg' => 'application/vnd.oasis.opendocument.graphics-template',
'otp' => 'application/vnd.oasis.opendocument.presentation-template',
'ots' => 'application/vnd.oasis.opendocument.spreadsheet-template',
'ott' => 'application/vnd.oasis.opendocument.text-template',
'pcx' => 'image/x-pcx',
'pdf' => 'application/pdf',
'png' => 'image/png',
'pot' => 'application/vnd.ms-powerpoint',
'potx' => 'application/vnd.openxmlformats-officedocument.presentationml.template',
'pps' => 'application/vnd.ms-powerpoint',
'ppsx' => 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
'ppt' => 'application/vnd.ms-powerpoint',
'pptx' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
'psd' => 'image/vnd.adobe.photoshop',
'rtf' => 'application/rtf',
'stc' => 'application/vnd.sun.xml.calc.template',
'std' => 'application/vnd.sun.xml.draw.template',
'sti' => 'application/vnd.sun.xml.impress.template',
'stw' => 'application/vnd.sun.xml.writer.template',
'swf' => 'application/x-shockwave-flash',
'svg' => 'image/svg+xml',
'xvgz' => 'image/svg+xml-compressed',
'sxc' => 'application/vnd.sun.xml.calc',
'sxd' => 'application/vnd.sun.xml.draw',
'sxg' => 'application/vnd.sun.xml.writer.global',
'sxi' => 'application/vnd.sun.xml.impress',
'sxm' => 'application/vnd.sun.xml.math',
'sxw' => 'application/vnd.sun.xml.writer',
'tif' => 'image/tiff',
'tiff' => 'image/tif',
'txt' => 'text/plain',
'wav' => 'audio/wav',
'wbmp' => 'image/vnd.wap.vbmp',
'wma' => 'audio/x-ms-wma',
'wmf' => 'image/x-wmf',
'wmv' => 'video/x-ms-wmv',
'wmx' => 'audio/x-ms-asx',
'xaml' => 'application/x-silverlight',
'xcf' => 'image/x-xcf',
'xls' => 'application/vnd.ms-excel',
'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
'xlt' => 'application/vnd.ms-excel',
'xltx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
'xpm' => 'image/x-xpixmap',
);
?>